// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/jot/pages/v1/pages.proto

package pagesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribePageRequest) Reset() {
	*x = SubscribePageRequest{}
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePageRequest) ProtoMessage() {}

func (x *SubscribePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePageRequest.ProtoReflect.Descriptor instead.
func (*SubscribePageRequest) Descriptor() ([]byte, []int) {
	return file_proto_jot_pages_v1_pages_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribePageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type PageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Page          *Page                  `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageEvent) Reset() {
	*x = PageEvent{}
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageEvent) ProtoMessage() {}

func (x *PageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageEvent.ProtoReflect.Descriptor instead.
func (*PageEvent) Descriptor() ([]byte, []int) {
	return file_proto_jot_pages_v1_pages_proto_rawDescGZIP(), []int{1}
}

func (x *PageEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PageEvent) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PageEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Blocks        []*Block               `protobuf:"bytes,4,rep,name=blocks,proto3" json:"blocks,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_proto_jot_pages_v1_pages_proto_rawDescGZIP(), []int{2}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *Page) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *Page) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Page) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Page) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PageId        string                 `protobuf:"bytes,2,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Position      int32                  `protobuf:"varint,5,opt,name=position,proto3" json:"position,omitempty"`
	DataJson      string                 `protobuf:"bytes,6,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_jot_pages_v1_pages_proto_rawDescGZIP(), []int{3}
}

func (x *Block) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *Block) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Block) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Block) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Block) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type CreatePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Cover         string                 `protobuf:"bytes,2,opt,name=cover,proto3" json:"cover,omitempty"`
	Blocks        []*Block               `protobuf:"bytes,3,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageRequest) Reset() {
	*x = CreatePageRequest{}
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageRequest) ProtoMessage() {}

func (x *CreatePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageRequest.ProtoReflect.Descriptor instead.
func (*CreatePageRequest) Descriptor() ([]byte, []int) {
	return file_proto_jot_pages_v1_pages_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePageRequest) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CreatePageRequest) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type CreatePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePageResponse) Reset() {
	*x = CreatePageResponse{}
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePageResponse) ProtoMessage() {}

func (x *CreatePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePageResponse.ProtoReflect.Descriptor instead.
func (*CreatePageResponse) Descriptor() ([]byte, []int) {
	return file_proto_jot_pages_v1_pages_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageRequest) Reset() {
	*x = GetPageRequest{}
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageRequest) ProtoMessage() {}

func (x *GetPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageRequest.ProtoReflect.Descriptor instead.
func (*GetPageRequest) Descriptor() ([]byte, []int) {
	return file_proto_jot_pages_v1_pages_proto_rawDescGZIP(), []int{6}
}

func (x *GetPageRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

type GetPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPageResponse) Reset() {
	*x = GetPageResponse{}
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPageResponse) ProtoMessage() {}

func (x *GetPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPageResponse.ProtoReflect.Descriptor instead.
func (*GetPageResponse) Descriptor() ([]byte, []int) {
	return file_proto_jot_pages_v1_pages_proto_rawDescGZIP(), []int{7}
}

func (x *GetPageResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type UpdateBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Blocks        []*Block               `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlocksRequest) Reset() {
	*x = UpdateBlocksRequest{}
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlocksRequest) ProtoMessage() {}

func (x *UpdateBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlocksRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlocksRequest) Descriptor() ([]byte, []int) {
	return file_proto_jot_pages_v1_pages_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBlocksRequest) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *UpdateBlocksRequest) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type UpdateBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlocksResponse) Reset() {
	*x = UpdateBlocksResponse{}
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlocksResponse) ProtoMessage() {}

func (x *UpdateBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_jot_pages_v1_pages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlocksResponse.ProtoReflect.Descriptor instead.
func (*UpdateBlocksResponse) Descriptor() ([]byte, []int) {
	return file_proto_jot_pages_v1_pages_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBlocksResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_proto_jot_pages_v1_pages_proto protoreflect.FileDescriptor

const file_proto_jot_pages_v1_pages_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/jot/pages/v1/pages.proto\x12\fjot.pages.v1\"/\n" +
	"\x14SubscribePageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"e\n" +
	"\tPageEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12&\n" +
	"\x04page\x18\x02 \x01(\v2\x12.jot.pages.v1.PageR\x04page\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\xcc\x01\n" +
	"\x04Page\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x03 \x01(\tR\x05cover\x12+\n" +
	"\x06blocks\x18\x04 \x03(\v2\x13.jot.pages.v1.BlockR\x06blocks\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\a \x01(\tR\tdeletedAt\"\x9a\x01\n" +
	"\x05Block\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\apage_id\x18\x02 \x01(\tR\x06pageId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\x05R\bposition\x12\x1b\n" +
	"\tdata_json\x18\x06 \x01(\tR\bdataJson\"l\n" +
	"\x11CreatePageRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05cover\x18\x02 \x01(\tR\x05cover\x12+\n" +
	"\x06blocks\x18\x03 \x03(\v2\x13.jot.pages.v1.BlockR\x06blocks\"<\n" +
	"\x12CreatePageResponse\x12&\n" +
	"\x04page\x18\x01 \x01(\v2\x12.jot.pages.v1.PageR\x04page\")\n" +
	"\x0eGetPageRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\"9\n" +
	"\x0fGetPageResponse\x12&\n" +
	"\x04page\x18\x01 \x01(\v2\x12.jot.pages.v1.PageR\x04page\"[\n" +
	"\x13UpdateBlocksRequest\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12+\n" +
	"\x06blocks\x18\x02 \x03(\v2\x13.jot.pages.v1.BlockR\x06blocks\">\n" +
	"\x14UpdateBlocksResponse\x12&\n" +
	"\x04page\x18\x01 \x01(\v2\x12.jot.pages.v1.PageR\x04page2_\n" +
	"\rPagesRealtime\x12N\n" +
	"\rSubscribePage\x12\".jot.pages.v1.SubscribePageRequest\x1a\x17.jot.pages.v1.PageEvent0\x012\xf7\x01\n" +
	"\x05Pages\x12O\n" +
	"\n" +
	"CreatePage\x12\x1f.jot.pages.v1.CreatePageRequest\x1a .jot.pages.v1.CreatePageResponse\x12F\n" +
	"\aGetPage\x12\x1c.jot.pages.v1.GetPageRequest\x1a\x1d.jot.pages.v1.GetPageResponse\x12U\n" +
	"\fUpdateBlocks\x12!.jot.pages.v1.UpdateBlocksRequest\x1a\".jot.pages.v1.UpdateBlocksResponseB6Z4github.com/reggieanim/jot/proto/jot/pages/v1;pagesv1b\x06proto3"

var (
	file_proto_jot_pages_v1_pages_proto_rawDescOnce sync.Once
	file_proto_jot_pages_v1_pages_proto_rawDescData []byte
)

func file_proto_jot_pages_v1_pages_proto_rawDescGZIP() []byte {
	file_proto_jot_pages_v1_pages_proto_rawDescOnce.Do(func() {
		file_proto_jot_pages_v1_pages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_jot_pages_v1_pages_proto_rawDesc), len(file_proto_jot_pages_v1_pages_proto_rawDesc)))
	})
	return file_proto_jot_pages_v1_pages_proto_rawDescData
}

var file_proto_jot_pages_v1_pages_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_jot_pages_v1_pages_proto_goTypes = []any{
	(*SubscribePageRequest)(nil), // 0: jot.pages.v1.SubscribePageRequest
	(*PageEvent)(nil),            // 1: jot.pages.v1.PageEvent
	(*Page)(nil),                 // 2: jot.pages.v1.Page
	(*Block)(nil),                // 3: jot.pages.v1.Block
	(*CreatePageRequest)(nil),    // 4: jot.pages.v1.CreatePageRequest
	(*CreatePageResponse)(nil),   // 5: jot.pages.v1.CreatePageResponse
	(*GetPageRequest)(nil),       // 6: jot.pages.v1.GetPageRequest
	(*GetPageResponse)(nil),      // 7: jot.pages.v1.GetPageResponse
	(*UpdateBlocksRequest)(nil),  // 8: jot.pages.v1.UpdateBlocksRequest
	(*UpdateBlocksResponse)(nil), // 9: jot.pages.v1.UpdateBlocksResponse
}
var file_proto_jot_pages_v1_pages_proto_depIdxs = []int32{
	2,  // 0: jot.pages.v1.PageEvent.page:type_name -> jot.pages.v1.Page
	3,  // 1: jot.pages.v1.Page.blocks:type_name -> jot.pages.v1.Block
	3,  // 2: jot.pages.v1.CreatePageRequest.blocks:type_name -> jot.pages.v1.Block
	2,  // 3: jot.pages.v1.CreatePageResponse.page:type_name -> jot.pages.v1.Page
	2,  // 4: jot.pages.v1.GetPageResponse.page:type_name -> jot.pages.v1.Page
	3,  // 5: jot.pages.v1.UpdateBlocksRequest.blocks:type_name -> jot.pages.v1.Block
	2,  // 6: jot.pages.v1.UpdateBlocksResponse.page:type_name -> jot.pages.v1.Page
	0,  // 7: jot.pages.v1.PagesRealtime.SubscribePage:input_type -> jot.pages.v1.SubscribePageRequest
	4,  // 8: jot.pages.v1.Pages.CreatePage:input_type -> jot.pages.v1.CreatePageRequest
	6,  // 9: jot.pages.v1.Pages.GetPage:input_type -> jot.pages.v1.GetPageRequest
	8,  // 10: jot.pages.v1.Pages.UpdateBlocks:input_type -> jot.pages.v1.UpdateBlocksRequest
	1,  // 11: jot.pages.v1.PagesRealtime.SubscribePage:output_type -> jot.pages.v1.PageEvent
	5,  // 12: jot.pages.v1.Pages.CreatePage:output_type -> jot.pages.v1.CreatePageResponse
	7,  // 13: jot.pages.v1.Pages.GetPage:output_type -> jot.pages.v1.GetPageResponse
	9,  // 14: jot.pages.v1.Pages.UpdateBlocks:output_type -> jot.pages.v1.UpdateBlocksResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_jot_pages_v1_pages_proto_init() }
func file_proto_jot_pages_v1_pages_proto_init() {
	if File_proto_jot_pages_v1_pages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_jot_pages_v1_pages_proto_rawDesc), len(file_proto_jot_pages_v1_pages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_jot_pages_v1_pages_proto_goTypes,
		DependencyIndexes: file_proto_jot_pages_v1_pages_proto_depIdxs,
		MessageInfos:      file_proto_jot_pages_v1_pages_proto_msgTypes,
	}.Build()
	File_proto_jot_pages_v1_pages_proto = out.File
	file_proto_jot_pages_v1_pages_proto_goTypes = nil
	file_proto_jot_pages_v1_pages_proto_depIdxs = nil
}
