// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/jot/pages/v1/pages.proto

package pagesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PagesRealtime_SubscribePage_FullMethodName = "/jot.pages.v1.PagesRealtime/SubscribePage"
)

// PagesRealtimeClient is the client API for PagesRealtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PagesRealtimeClient interface {
	SubscribePage(ctx context.Context, in *SubscribePageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PageEvent], error)
}

type pagesRealtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewPagesRealtimeClient(cc grpc.ClientConnInterface) PagesRealtimeClient {
	return &pagesRealtimeClient{cc}
}

func (c *pagesRealtimeClient) SubscribePage(ctx context.Context, in *SubscribePageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PageEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PagesRealtime_ServiceDesc.Streams[0], PagesRealtime_SubscribePage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribePageRequest, PageEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PagesRealtime_SubscribePageClient = grpc.ServerStreamingClient[PageEvent]

// PagesRealtimeServer is the server API for PagesRealtime service.
// All implementations must embed UnimplementedPagesRealtimeServer
// for forward compatibility.
type PagesRealtimeServer interface {
	SubscribePage(*SubscribePageRequest, grpc.ServerStreamingServer[PageEvent]) error
	mustEmbedUnimplementedPagesRealtimeServer()
}

// UnimplementedPagesRealtimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPagesRealtimeServer struct{}

func (UnimplementedPagesRealtimeServer) SubscribePage(*SubscribePageRequest, grpc.ServerStreamingServer[PageEvent]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribePage not implemented")
}
func (UnimplementedPagesRealtimeServer) mustEmbedUnimplementedPagesRealtimeServer() {}
func (UnimplementedPagesRealtimeServer) testEmbeddedByValue()                       {}

// UnsafePagesRealtimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PagesRealtimeServer will
// result in compilation errors.
type UnsafePagesRealtimeServer interface {
	mustEmbedUnimplementedPagesRealtimeServer()
}

func RegisterPagesRealtimeServer(s grpc.ServiceRegistrar, srv PagesRealtimeServer) {
	// If the following call pancis, it indicates UnimplementedPagesRealtimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PagesRealtime_ServiceDesc, srv)
}

func _PagesRealtime_SubscribePage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribePageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PagesRealtimeServer).SubscribePage(m, &grpc.GenericServerStream[SubscribePageRequest, PageEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PagesRealtime_SubscribePageServer = grpc.ServerStreamingServer[PageEvent]

// PagesRealtime_ServiceDesc is the grpc.ServiceDesc for PagesRealtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PagesRealtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jot.pages.v1.PagesRealtime",
	HandlerType: (*PagesRealtimeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribePage",
			Handler:       _PagesRealtime_SubscribePage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/jot/pages/v1/pages.proto",
}

const (
	Pages_CreatePage_FullMethodName   = "/jot.pages.v1.Pages/CreatePage"
	Pages_GetPage_FullMethodName      = "/jot.pages.v1.Pages/GetPage"
	Pages_UpdateBlocks_FullMethodName = "/jot.pages.v1.Pages/UpdateBlocks"
)

// PagesClient is the client API for Pages service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PagesClient interface {
	CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*CreatePageResponse, error)
	GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*GetPageResponse, error)
	UpdateBlocks(ctx context.Context, in *UpdateBlocksRequest, opts ...grpc.CallOption) (*UpdateBlocksResponse, error)
}

type pagesClient struct {
	cc grpc.ClientConnInterface
}

func NewPagesClient(cc grpc.ClientConnInterface) PagesClient {
	return &pagesClient{cc}
}

func (c *pagesClient) CreatePage(ctx context.Context, in *CreatePageRequest, opts ...grpc.CallOption) (*CreatePageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePageResponse)
	err := c.cc.Invoke(ctx, Pages_CreatePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagesClient) GetPage(ctx context.Context, in *GetPageRequest, opts ...grpc.CallOption) (*GetPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPageResponse)
	err := c.cc.Invoke(ctx, Pages_GetPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pagesClient) UpdateBlocks(ctx context.Context, in *UpdateBlocksRequest, opts ...grpc.CallOption) (*UpdateBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBlocksResponse)
	err := c.cc.Invoke(ctx, Pages_UpdateBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PagesServer is the server API for Pages service.
// All implementations must embed UnimplementedPagesServer
// for forward compatibility.
type PagesServer interface {
	CreatePage(context.Context, *CreatePageRequest) (*CreatePageResponse, error)
	GetPage(context.Context, *GetPageRequest) (*GetPageResponse, error)
	UpdateBlocks(context.Context, *UpdateBlocksRequest) (*UpdateBlocksResponse, error)
	mustEmbedUnimplementedPagesServer()
}

// UnimplementedPagesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPagesServer struct{}

func (UnimplementedPagesServer) CreatePage(context.Context, *CreatePageRequest) (*CreatePageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePage not implemented")
}
func (UnimplementedPagesServer) GetPage(context.Context, *GetPageRequest) (*GetPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (UnimplementedPagesServer) UpdateBlocks(context.Context, *UpdateBlocksRequest) (*UpdateBlocksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBlocks not implemented")
}
func (UnimplementedPagesServer) mustEmbedUnimplementedPagesServer() {}
func (UnimplementedPagesServer) testEmbeddedByValue()               {}

// UnsafePagesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PagesServer will
// result in compilation errors.
type UnsafePagesServer interface {
	mustEmbedUnimplementedPagesServer()
}

func RegisterPagesServer(s grpc.ServiceRegistrar, srv PagesServer) {
	// If the following call pancis, it indicates UnimplementedPagesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Pages_ServiceDesc, srv)
}

func _Pages_CreatePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).CreatePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pages_CreatePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).CreatePage(ctx, req.(*CreatePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pages_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pages_GetPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).GetPage(ctx, req.(*GetPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pages_UpdateBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PagesServer).UpdateBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pages_UpdateBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PagesServer).UpdateBlocks(ctx, req.(*UpdateBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Pages_ServiceDesc is the grpc.ServiceDesc for Pages service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pages_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jot.pages.v1.Pages",
	HandlerType: (*PagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePage",
			Handler:    _Pages_CreatePage_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _Pages_GetPage_Handler,
		},
		{
			MethodName: "UpdateBlocks",
			Handler:    _Pages_UpdateBlocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/jot/pages/v1/pages.proto",
}
